Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace ClothingStore.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/SneakersController.cs
using ClothingStore.Models;
using ClothingStore.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ClothingStore.Controllers
{
    public class SneakersController : Controller
    {
        private readonly ISneakersRepository _sneakersRepository;
        private readonly ICategoryRepository _categoryRepository;

        public SneakersController (ISneakersRepository sneakersRepository, ICategoryRepository categoryRepository)
        {
            _sneakersRepository = sneakersRepository;
            _categoryRepository = categoryRepository;
        }

       // public IActionResult List()
        //{
          //  SneakersListViewModel sneakersListViewModel = new SneakersListViewModel(_sneakersRepository.AllSneakers, "All Shoes");
            //return View(sneakersListViewModel);
        //}

        public ViewResult List(string category)
        {
            IEnumerable<Sneakers> sneakers;
            string? currentCategory;

            if(string.IsNullOrEmpty(category))
            {
                sneakers = _sneakersRepository.AllSneakers.OrderBy(p => p.SneakersId);
                currentCategory = "All Sneakers";
            }
            else
            {
                sneakers = _sneakersRepository.AllSneakers.Where(p => p.Category.CategoryName ==
                category).OrderBy(p => p.SneakersId);
                currentCategory = _categoryRepository.AllCategories.FirstOrDefault(c =>
                c.CategoryName == category)?.CategoryName;
            }

            return View(new SneakersListViewModel(sneakers, currentCategory));
        }

        public IActionResult Details(int id)
        {
            var sneakers = _sneakersRepository.GetSneakersById(id);
            if (sneakers == null)
                return NotFound();
            
            return View(sneakers);

        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Damons Dapper Boutique</title>
    <link href='https://fonts.googleapis.com/css?family=Work+Sans' rel='stylesheet' type='text/css'>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/css/site.css" rel="stylesheet" />
    <base href="/" />
</head>
<body>
    <div class="container">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-primary"
                 aria-label="Bethany's Pie Shop navigation header">
                <div class="container-xl">
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                        <img src="images/bethanys-pie-shop-logo_horiz-white.png" width="151" height="47" class="d-inline-block align-top mb-2 mt-1"
                             alt="Damons Sneaker Boutique">
                    </a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <vc:category-menu></vc:category-menu>
                             <li class="nav-item">
                                <a asp-controller="Contact" asp-action="Index" class="nav-link">Contact</a>
                            </li>
                        </ul>
                        <vc:shopping-cart-summary></vc:shopping-cart-summary>
                    </div>
                </div>
            </nav>
        </header>

        @RenderBody()
    </div>
</body>
</html>

Views/Shared/_SneakersCard.cshtml
@model Sneakers
<div class="col">
    <div class="card sneakers-card">
        <img src="@Model.ImageThumbnailURL" class="card-img-top" alt="@Model.Name">
        <div class="card-body sneakers-button">
            <h4 class="d-grid">
                <a class="btn btn-secondary" 
                   asp-controller="ShoppingCart" 
                   asp-action="AddToShoppingCart"
                   asp-route-SneakersId="@Model.SneakersId"> + Add to cart</a>
            </h4>
            
            <div class="d-flex justify-content-between mt-2">
                <h2 class="text-start">
                    <a asp-controller="Sneakers"
                       asp-action="Details"
                       asp-route-id="@Model.SneakersId"
                       class="sneakers-link">@Model.Name</a>
                </h2>
                 <h5 class="text-nowrap">
                    @Model.Price.ToString("c")
                </h5>
            </div>
        </div>
    </div>
</div>